### ISSUE TITLE
thread safe for iOS  

### ISSUE THREAD

**Issue by JuhnGJ** [beeware/Python-Apple-support#71] opened 2019-03-29 09:17 UTC
I can't run more than two instance objects at the same time, otherwise it will crash, can give me some suggestions, thank you!

**Comment by freakboy3742** [comment] 2019-03-29 23:14
We're going to need a little more detail - what do you mean by "more than two instance objects"?

**Comment by fangyuxi** [comment] 2020-06-17 11:58
@JuhnGJ @freakboy3742 

I am facing the same problem, I am using this library in iOS, below is the code snippet

If I encapsulate the getInfoWithId method in NSOperation (remove the GIL-related code), and then execute it in parallel with NSOperationQueue, then it will be Crash. If I use GIL, it will not be Crash, but if I use GIL, it will become serial .

Is the current library not thread-safe?

` - (NSDictionary *)getInfoWithId:(NSString *)audioId{
    
    if (![audioId isNotBlank]) {
        return nil;
    }
    
    PyGILState_STATE state = PyGILState_Ensure();
    
    PyObject *module1 = [PMPythonEngine sharedInstance].module1;
    PyObject *module2 = [PMPythonEngine sharedInstance].module2;
    
    PyObject *xxObject1ClassDic = PyModule_GetDict(xxObject1);
    PyObject *xxObject2ClassDic = PyModule_GetDict(xxObject2);
    
    PyObject *xxObject1ClassObject = PyDict_GetItemString(xxObject1ClassDic,[@"classname" UTF8String]);
    PyObject *xxObject1Instance = PyObject_CallObject(xxObject1ClassObject, NULL);
    
    PyObject *pRet = PyObject_CallMethod(xxObject1ClassObject, (char *)[@"method" UTF8String], "OsO", xxObject1Instance,[audioId UTF8String],Py_BuildValue("O", Py_False));
    
    PyGILState_Release(state);

    return dic;
}  `

**Comment by freakboy3742** [comment] 2020-06-17 12:48
I'm not sure what you mean by "not thread safe" in this context. There isn't anything special about Python-Apple-support in this regard; it's the standard CPython embedding API. Python's GIL exists specifically because of threading concerns, and using the GIL is how you make a sequence of Python-using code threadsafe.

Closing this ticket on the basis that it sounds like it's behaving exactly as designed; and the original request hasn't provided any follow up information.

**Closed by freakboy3742** 2020-06-17 12:48 UTC
