### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by full-of-fire** [beeware/Python-Apple-support#95] opened 2020-07-22 10:58 UTC
**Describe the bug**
ld: symbol(s) not found for architecture x86_64

**To Reproduce**
I use Python-Apple-support to run make macOS and then add the files in Support to the App project of macOS. An error is reported when compiling. Can you help me see this problem? Thank you very much.
**Detail**
Undefined symbols for architecture x86_64:
  "_libintl_bind_textdomain_codeset", referenced from:
      _PyIntl_bind_textdomain_codeset in libPython.a(_localemodule.o)
  "_libintl_bindtextdomain", referenced from:
      _PyIntl_bindtextdomain in libPython.a(_localemodule.o)
  "_libintl_dcgettext", referenced from:
      _PyIntl_dcgettext in libPython.a(_localemodule.o)
  "_libintl_dgettext", referenced from:
      _PyIntl_dgettext in libPython.a(_localemodule.o)
  "_libintl_gettext", referenced from:
      _PyIntl_gettext in libPython.a(_localemodule.o)
  "_libintl_setlocale", referenced from:
      _PyLocale_setlocale in libPython.a(_localemodule.o)
      _PyLocale_localeconv in libPython.a(_localemodule.o)
  "_libintl_textdomain", referenced from:
      _PyIntl_textdomain in libPython.a(_localemodule.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation

**Comment by freakboy3742** [comment] 2020-07-22 11:14
Sounds like you've got gettext in your developer environment when you run the compilation. For some reason, we can't convince the build script to ignore that dependency if it is present.

**Comment by full-of-fire** [comment] 2020-07-22 11:39
But I removed the files in the Support and compiled it normally. I really don’t know how to solve it. I’ll try to find other methods again, Thanks for the reply！

**Comment by freakboy3742** [comment] 2021-01-02 04:39
This appears to be a duplicate of #91, which has now been resolved.

**Closed by freakboy3742** 2021-01-02 04:39 UTC
Labels: bug
