### ISSUE TITLE
Add numpy error

### ISSUE THREAD

**Issue by LengQH** [beeware/Python-Apple-support#136] opened 2022-03-23 16:26 UTC
<img width="1117" alt="图片" src="https://user-images.githubusercontent.com/13087205/159747799-b7995bc8-8507-4279-b65b-6e7ce28ab4e4.png">

# Install requirements for compiling Numpy
/Users/lisen/Desktop/Python_iOS/Python-Apple-support-3.9_1/build/macOS/Python-3.9.6-macOS/dist/bin/pip3 install cython
Requirement already satisfied: cython in ./build/macOS/Python-3.9.6-macOS/dist/lib/python3.9/site-packages (0.29.28)
WARNING: You are using pip version 21.1.3; however, version 22.0.4 is available.
You should consider upgrading via the '/Users/lisen/Desktop/Python_iOS/Python-Apple-support-3.9_1/build/macOS/Python-3.9.6-macOS/dist/bin/python3 -m pip install --upgrade pip' command.
cd build/macOS/packages/numpy && BLAS=None LAPACK=None ATLAS=None /Users/lisen/Desktop/Python_iOS/Python-Apple-support-3.9_1/build/macOS/Python-3.9.6-macOS/dist/bin/pip3 install --target /Users/lisen/Desktop/Python_iOS/Python-Apple-support-3.9_1/dist/app_packages .
Processing /Users/lisen/Desktop/Python_iOS/Python-Apple-support-3.9_1/build/macOS/packages/numpy
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Using legacy 'setup.py install' for numpy, since package 'wheel' is not installed.
Installing collected packages: numpy
    Running setup.py install for numpy ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/lisen/Desktop/Python_iOS/Python-Apple-support-3.9_1/build/macOS/Python-3.9.6-macOS/dist/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7j/q1cd9_qs4px0x28rnxpzqft40000gn/T/pip-req-build-y6uygbay/setup.py'"'"'; __file__='"'"'/private/var/folders/7j/q1cd9_qs4px0x28rnxpzqft40000gn/T/pip-req-build-y6uygbay/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/7j/q1cd9_qs4px0x28rnxpzqft40000gn/T/pip-record-vq4gag9q/install-record.txt --single-version-externally-managed --home /private/var/folders/7j/q1cd9_qs4px0x28rnxpzqft40000gn/T/pip-target-q805o9wv --compile --install-headers /private/var/folders/7j/q1cd9_qs4px0x28rnxpzqft40000gn/T/pip-target-q805o9wv/include/python/numpy
         cwd: /private/var/folders/7j/q1cd9_qs4px0x28rnxpzqft40000gn/T/pip-req-build-y6uygbay/
    Complete output (4038 lines):
    Running from numpy source directory.
    
    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:
    
      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install numpy`   (last NumPy release on PyPi)
    
    
    /private/var/folders/7j/q1cd9_qs4px0x28rnxpzqft40000gn/T/pip-req-build-y6uygbay/numpy/distutils/misc_util.py:464: SyntaxWarning: "is" with a literal. Did you mean "=="?
      return is_string(s) and ('*' in s or '?' is s)
    blas_opt_info:
    blas_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/Users/lisen/Desktop/Python_iOS/Python-Apple-support-3.9_1/build/macOS/Python-3.9.6-macOS/dist/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE
    
    blis_info:
    customize UnixCCompiler
      libraries blis not found in ['/Users/lisen/Desktop/Python_iOS/Python-Apple-support-3.9_1/build/macOS/Python-3.9.6-macOS/dist/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

**Comment by freakboy3742** [comment] 2022-03-23 22:47
Duplicate of #134 and #135.

Once again, you've opened a bug report - but I have no idea what you're doing, or how you've generated the error you're reporting. 

When you open a new bug, you are presented with a bug template. This template gives a number of writing prompts - a description of the problem you're having, steps to reproduce the problem, the behaviour you expect, and so on. 

That template exists for a reason. It captures the *bare minimum* information we need to be able to do anything to help you. If you don't fill out the template, it is highly unlikely we're going to be able to help you.

You are making a conscious choice to *delete* the content of the template. That fundamentally prevents us from helping you.

In this case - it's clear you're doing something with numpy - but that is all that is all I can work out. I've already pointed you at a ticket that describes the fact that modules with binary dependencies are difficult to install - and numpy is one big binary dependency.

**Closed by freakboy3742** 2022-03-23 22:47 UTC
Labels: bug
