### ISSUE TITLE
How to import third-party libraries on iOS, such as numpy  (Python_3.10)

### ISSUE THREAD

**Issue by LengQH** [beeware/Python-Apple-support#135] opened 2022-03-22 06:01 UTC
How to import third-party libraries on iOS, such as numpy  (Python_3.10)

<img width="1012" alt="图片" src="https://user-images.githubusercontent.com/13087205/159417582-221947fc-4883-4163-95e0-c40839b63b0e.png">

**Comment by freakboy3742** [comment] 2022-03-22 06:04
Duplicate of #134.

If it's a pure python library, you can just import.

If the library contains a binary component, the answer is "you can't" for now. See beeware/briefcase#471 for details.

**Closed by freakboy3742** 2022-03-22 06:04 UTC
Labels: invalid
